### ISSUE TITLE
Add cr1000x for amigos III

### ISSUE THREAD

**Issue by wallinb** [wallinb/amigos3#1]
Need to read data over network connection for:

- Snow height
- 8 Thermistors
- Voltage
- Temperature

**Comment by wallinb** [comment]
Could be useful: https://pypi.org/projectproject/PyCampbellCR1000/

**Comment by CooviM** [comment]
Data can be acquired from the CR1000 using Linux and Ethernet link. 
The Library in the comment above works fine.
One issue is the signal strength depends on the ethernet cable length. If the cable is too long, no communication can be made.

**Comment by CooviM** [comment]
The cr1000x library is working on the board

**Comment by wallinb** [comment]
@CooviM Did we test the long cable uncoiled outside? The communication problem could just have been interference in the lab from all the equipment. It is surprising if length is actually the problem.

**Comment by wallinb** [comment]
I think Ryan mentioned the issue was something with the battery box and is now resolved, i. e. the cr1000x are now working with the long cables. Closing.
