### ISSUE TITLE
Read from Triton onboard sensors

### ISSUE THREAD

**Issue by wallinb** [wallinb/amigos3#15]
The Triton board has on board sensors including humidity, temperature, voltage, and accelerometer sensors.  Implement python code that reads data from these sensors.

Some explanation for temperature/humidity readings can be found [here](https://github.com/wallinb/amigos3/wiki/files/Triton3_9260_output_control.pdf).

**Comment by CooviM** [comment]
I will write the code for the temp and humidity sensor on the Tritron borad but the accelerometer will be out on hold as I do not know the location where the data are saved on the board for now

**Comment by wallinb** [comment]
@CooviM But voltage and current can be measured?

**Comment by CooviM** [comment]
Incorporated the Temp and Humidity sensor
