### ISSUE TITLE
Ensure board recovers from voltage fluxuations

### ISSUE THREAD

**Issue by wallinb** [wallinb/amigos3#20]
- [ ] When voltage drops below a minimum level the board should shut down gracefully if possible (try to finish running scheduled commands, log low power event, power down)

- [ ] When voltage returns to adequate level the station should "wake up" and be operational

**Comment by CooviM** [comment]
On the first point, note shutting down the board is doable but not appropriate. The power would need to be unplugged and plugged back in for the board to run again. This can not be done in the field. 
However, we can pause the schedule (power off all peripheral) when the last SBD message is sent if the voltage drop under the threshold (let say 10 V). All devices powered up at 10 V (Camera and CR1000x not tested)
