### ISSUE TITLE
Internet freeze after board goes to sleep

### ISSUE THREAD

**Issue by CooviM** [wallinb/amigos3#5]
I was noticed that after the board wake from sleep the internet route from the board to the route become unavailable or freeze.
The temporary solution implemented at this time is to reboot the boot after awaken but this not the desired outcome.

**Comment by wallinb** [comment]
@CooviM Is this still an issue?

**Comment by CooviM** [comment]
Yes, we have not address it yet as it is not a top priority. My solution was to restart the board after the sleep time.
